<!-- PY-AI-ML-HEADER -->
# 📘 NumPy & Pandas
## 📝 Lec 03 Numpy Misc Practice

> **Series:** Python for AI/ML &nbsp;|&nbsp; **Author:** Sriyut Singh &nbsp;|&nbsp; **Folder:** `05-numpy-and-pandas`

---
### 👇 Code & Output Below


In [40]:
import numpy as n
a = n.diag([6,12,18,24])

In [41]:
print(a)

[[ 6  0  0  0]
 [ 0 12  0  0]
 [ 0  0 18  0]
 [ 0  0  0 24]]


In [43]:
a[2],[1]

(array([ 0,  0, 18,  0]), [1])

In [31]:
2+3

5

In [39]:
a= n.arange(1)
%timeit [5*55+666-555/33+2222]

78.3 ns ± 0.695 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [33]:
6/5


1.2

In [34]:
2*5

10

In [35]:
1.2+10

11.2