<!-- PY-AI-ML-HEADER -->
# 📘 NumPy & Pandas
## 📝 Lec 01 Numpy

> **Series:** Python for AI/ML &nbsp;|&nbsp; **Author:** Sriyut Singh &nbsp;|&nbsp; **Folder:** `05-numpy-and-pandas`

---
### 👇 Code & Output Below


# NUM PY AND PANDA 

### numerical python is num py

### num py is much better as list it does the work much faster than list

###### it is as array

###### also known as array oriented computing

In [1]:
import numpy as np

type(np.array(['sriyut',2,3]))

np.array([1,2,3,4.0])

array([1., 2., 3., 4.])

### two dimentions

In [2]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [3]:
import numpy as np
a = np.array([0,1,2,3])
print(a)
print(type(a))
print(np.arange(10))
#the range of numpy is arange

[0 1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [4]:
import time

import time as a
print(a.time())
l = range(1000)
[i**2 for i in l]  
print(a.time())

1616421204.1271281
1616421204.1281292


In [5]:
import time
a=time.time()
l=range(1000)
[i**2 for i in l]
b=time.time()
d=b-a
print(d)

0.0


In [8]:
x=time.time()
e= np.arange(1000)
d**2
y=time.time()
z=y-x
print(z)

0.0


# as we can see how much second it takes

In [10]:
l = range(1000)
%timeit [i**2 for i in l]

379 µs ± 3.56 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
a = np.arange(1000)
%timeit a**2

2.77 µs ± 48.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#  MATRIX

In [12]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b= np.arange(1,10,2)

b

array([1, 3, 5, 7, 9])

In [14]:
# using linspace

a = np.linspace(0,1,6) #start, end,number of points

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [15]:
a = np.linspace(1,50,20)
a

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [16]:
# common arrays

a = np.ones((3,3))#matrics  #row,column
#have to pass the value in tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
type(a)

numpy.ndarray

In [18]:
#type casting
b = np.ones((3,3),dtype=int)

print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [19]:
#identity matix

c= np.eye(3)

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#diagonal matrix

a = np.diag([1,2,3,4])

a

np.diag(a)  #Extracted diagonals

array([1, 2, 3, 4])

In [21]:
#creating an array using random

a = np.random.rand(4) 

a

array([0.07880578, 0.42091163, 0.19559625, 0.68984388])

In [22]:
# Data types

a= np.arange(10)

a.dtype

dtype('int32')

In [23]:
#you can explicitly specify which datatype you want:

a= np.arange(10,dtype='float64')

a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
d = np.array([1+2j, 2+4j]) #complex datatype

d.dtype

dtype('complex128')

In [25]:
b = np.array([True,False])

b.dtype

dtype('bool')

In [26]:
c = np.array(('1','2gcvgyvcccccccy'))

c.dtype

dtype('<U15')

In [27]:
# Indexing and slicing

a = np.arange(10)

print(a[1:5])

print('this the the index test',a[9])

[1 2 3 4]
this the the index test 9


In [28]:
a = np.diag([1,2,3])
print(a)
print(a[2,2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [29]:
#three dimentions matrix

c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [30]:
a='https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:mat-intro/a/intro-to-matrices'
a

'https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:mat-intro/a/intro-to-matrices'

In [31]:
a = np.diag([1,2,3])
print(a)
print(a[2,2])
a[2,1]= 5#assigning value

a

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [33]:
a = np.arange(10)

print(a)

a[1:8:2]

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7])

In [34]:
a = np.arange(10)
a[5:]=10#after 5 position all the numbers would be 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [37]:
b = np.arange(5)

a[5:] = b[::-1]#assigning

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [39]:
print(b)

#creating an array using random

a = np.random.rand(4) 

a

[0 1 2 3 4]


array([0.07800573, 0.09657211, 0.70919618, 0.31836695])

In [40]:
# Data types

a= np.arange(10)

a.dtype

dtype('int32')

In [41]:
#you can explicitly specify which datatype you want:

a= np.arange(10,dtype='float64')

a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
b = np.array([True,False])

b.dtype

dtype('bool')

In [44]:
c = np.array(('1','2gcvgyvcccccccy'))

c.dtype

dtype('<U15')

In [45]:
# Indexing and slicing

a = np.arange(10)

print(a[1:5])

print('this the the index test',a[9])

[1 2 3 4]
this the the index test 9


In [46]:
a = np.diag([1,2,3])
print(a)
print(a[2,2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [47]:
#three dimentions matrix

c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
a='https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:mat-intro/a/intro-to-matrices'
a

'https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:mat-intro/a/intro-to-matrices'

In [49]:
a = np.diag([1,2,3])
print(a)
print(a[2,2])
a[2,1]= 5#assigning value

a

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [50]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a[1:8:2]

array([1, 3, 5, 7])

In [52]:
a = np.arange(10)
a[5:]=10#after 5 position all the numbers would be 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [54]:
b = np.arange(5)

a[5:] = b[::-1]#assigning

print(a)

print(b)

[0 1 2 3 4 4 3 2 1 0]
[0 1 2 3 4]


In [55]:
#  Copies and Views

import numpy as np
a= np.arange(10)
print(a)
b = a[::2]
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [56]:
id(a)

24518979456

In [57]:
id(b)

24519008944

In [58]:
np.shares_memory(a,b)

True

In [59]:
b[0] = 10
print(b)
a

[10  2  4  6  8]


array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [60]:
a = np.arange(10)
print(a)
c = a[::2].copy()  #force a copy

print(c)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [61]:
np.shares_memory(a,c)
#copy changes only the values which you want

False

# Fancy indexing

#### Using Boolean mask

In [62]:
a = np.random.randint(0,20,15)
a

array([ 6,  2, 15, 19, 15,  7,  9, 12, 11, 11, 14, 11,  6, 14,  8])

In [63]:
mask = (a % 2 == 0)

mask

array([ True,  True, False, False, False, False, False,  True, False,
       False,  True, False,  True,  True,  True])

In [64]:
b = a[mask]
b

array([ 6,  2, 12, 14,  6, 14,  8])

In [66]:
a= np.array([1,2,3,4,5,6])

print(a + 1)

print(a -1)

print(a * 2)

print(a**2)

print(a/2)

print(a%2)

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 2  4  6  8 10 12]
[ 1  4  9 16 25 36]
[0.5 1.  1.5 2.  2.5 3. ]
[1 0 1 0 1 0]


In [67]:
b = np.ones(6) + 1
print(b)
a - b

a * b

[2. 2. 2. 2. 2. 2.]


array([ 2.,  4.,  6.,  8., 10., 12.])

In [68]:
#matrix multipication

c = np.diag([1,2,3,4])

print(c * c)
print('***************')
print(c.dot(c))#matrix multipication

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
***************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [69]:
d = np.diag([2,6,12,222])
print(c.dot(d))

[[  2   0   0   0]
 [  0  12   0   0]
 [  0   0  36   0]
 [  0   0   0 888]]


In [70]:
import numpy as np
np.matmul(c,d)

array([[  2,   0,   0,   0],
       [  0,  12,   0,   0],
       [  0,   0,  36,   0],
       [  0,   0,   0, 888]])

###### Comprasion

In [73]:
a= np.array([1,2,3,4])
b = np.array([2,4,5,4])

print(a == b)

print(a > b)

print(b > a)

np.array_equal(a,b)

[False False False  True]
[False False False False]
[ True  True  True False]


False

In [74]:
x,y=4,4
result=x*x+2*x*y+y*y
print("({}+{})^2)={}".format(x,y,result))
#doubt

(4+4)^2)=64


# Elementwise operations

In [75]:
import numpy as np

###### Logical operations

In [77]:
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)

print(np.logical_or(a,b))

print(np.logical_and(a,b))

[ True  True  True False]
[ True False False False]


###### Transcendental function:

In [79]:
a = np.arange(5)

print(np.sin(a))

print(np.log(a))

print(np.exp(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


<ipython-input-79-ebf3bc63d374>:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))


#### Shapc Mismatch

In [80]:
a = np.arange(4)
print(a.shape)

a + np.array([1,2])

(4,)


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [81]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [82]:
a = np.array([[10,2], [3,4]])
np.sum(a)

19

In [83]:
a.sum(axis=0) #column first dimention

array([13,  6])

In [84]:
a.sum(axis=1) #rows (second dimention)

array([12,  7])

In [86]:
x = np.array([[11,1],[2,22]])
print(x)

x.sum()

[[11  1]
 [ 2 22]]


36

In [87]:
b = np.array([1,2,3,4])
print(b.max())
print(b.min())

4
1


#####  argmax

In [89]:
print(b.argmin())#index position of the minimum number 

print(b.argmax())#index position of the maximum number

np.all([True,True,False])

np.any([True,False,False])

0
3


True

##### array comprasion

In [90]:
a = np.zeros((30,30))
print(a)
np.any(a != 0)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

False

In [91]:
np.all(a == a)

True

In [92]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [93]:
x.mean()

9.0

In [94]:
y =np.array([[1,2,3], [5,6,1]])
y.mean()

3.0

In [95]:
np.median(y,axis=1)

array([2., 5.])

# Standard deviation 

1. Work out the Mean (the simple average of the numbers)
2. Then for each number: subtract the Mean and square the result
3. Then work out the mean of those squared differences.
4. Take the square root of that and we are done!

For example 

In [96]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
print('this is the array')
print(a)
print('this is the process...')
b=a.mean()
print('this the the mean...',b)
print(a[::1]-b)
c= a**2
print('this is the square of all the number...',c)
print('this the the standard devation of the number...')
print(c.sum())

this is the array
[ 1  2  3  4  5  6  7  8  9 10]
this is the process...
this the the mean... 5.5
[-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
this is the square of all the number... [  1   4   9  16  25  36  49  64  81 100]
this the the standard devation of the number...
385


# MODE

Mode is the highest value between the data

In [97]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
a.max()

9